### ISSUE TITLE
Scrape for unassigned members, assign to New Members role

### ISSUE THREAD

**Issue by AndrewRathbun** [Digital-Forensics-Discord-Server/DiscordBot#7]
Dyno Bot sometimes fails to assign a new member to the New Members role. It's set up to assign that after 60 seconds of being in the server. Every now and then I'll notice a few "Online" members who don't have a role assigned, and therefore they have access to the entire server without having been assigned a role. If there's any way we can automate this, that would be a huge burden off the modstaff.

**Comment by mdawsonuk** [comment]
Should be easy enough to do, I can hook into the on member join callback and do that with our bot, should be much less prone to failing like Dyno due to the fact the bit will only be on one server.
